### ISSUE TITLE
Can't login after deploying Dex manifests to a private GKE cluster

### ISSUE THREAD

**Issue by rafaelbarreto87** [kubeflow/manifests#911]
I'm currently trying to deploy the Dex version of Kubeflow 1.0RC (https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml) to a GKE _private cluster_. Since private GKE clusters don't have internet access, I edited the manifests to point to copies of the images moved to our private gcr.io repository. The deployment finishes. however, when I try to load Kubeflow UI, I see this:

<img width="1920" alt="Screen Shot 2020-02-13 at 10 36 34 AM" src="https://user-images.githubusercontent.com/367830/74467540-1a11a100-4e4e-11ea-977f-22fc8272682f.png">

I'm using port-forward to access the UI after deployment because I can't create a load balancer just yet (not until I secure the deployment).

Looking at the source of that page, I see this:

```
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>dex</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="http://dex.auth.svc.cluster.local:5556/dex/static/main.css" rel="stylesheet">
    <link href="http://dex.auth.svc.cluster.local:5556/dex/theme/styles.css" rel="stylesheet">
    <link rel="icon" href="http://dex.auth.svc.cluster.local:5556/dex/theme/favicon.png">
  </head>  <body class="theme-body">
    <div class="theme-navbar">
      <div class="theme-navbar__logo-wrap">
        <img class="theme-navbar__logo" src="http://dex.auth.svc.cluster.local:5556/dex/theme/logo.png">
```

Note the references to static assets pointing to services in the cluster. This does seem right since for this to work I would have to expose those services through port-forward as well, right?

I initially thought this was a minor bug and wouldn't be a problem login in, but it does not work. When I try to login, I get a blank page and I see this in the logs:

```
kubectl logs -n istio-system -l app=authservice
time="2020-02-13T18:40:50Z" level=info msg="Starting web server at :8080"
time="2020-02-13T18:41:46Z" level=info msg="URI is whitelisted. Accepted without authorization." ip=10.8.0.69 request="/dex/auth/local?req=yqhnkktyg76suiuobjvs63xba"
time="2020-02-13T18:41:56Z" level=info msg="URI is whitelisted. Accepted without authorization." ip=10.8.0.69 request="/dex/auth/local?req=yqhnkktyg76suiuobjvs63xba"
time="2020-02-13T18:41:57Z" level=info msg="URI is whitelisted. Accepted without authorization." ip=10.8.0.69 request="/dex/approval?req=yqhnkktyg76suiuobjvs63xba"
time="2020-02-13T18:41:57Z" level=error msg="Not able to fetch userinfo: oidc: user info endpoint is not supported by this provider" ip=10.8.0.69 request="/login/oidc?code=iletnpf3kaiobfh6j6ijp6gkd&state=MTU4MTYxODg2MHxFd3dBRUhkNlJHdG9PV2d5Wm1obVZWWjFVems9fAU3iAAh1aHzfn2UOl01DHZLvR4m9cfT-FWOEPDQMtSP"
```

This exact same deployment works just fine if the cluster is not private.

Has anyone faced a similar problem deploying the Dex manifests? Am I doing something wrong or is this a potential bug?

**Comment by rafaelbarreto87** [comment]
Some additional logs:

```
kubectl logs -n auth -l app=dex
time="2020-02-13T18:30:14Z" level=info msg="custom resource already created offlinesessionses.dex.coreos.com"
time="2020-02-13T18:30:14Z" level=info msg="custom resource already created connectors.dex.coreos.com"
time="2020-02-13T18:30:14Z" level=info msg="config storage: kubernetes"
time="2020-02-13T18:30:14Z" level=info msg="config static client: kubeflow-oidc-authservice"
time="2020-02-13T18:30:14Z" level=info msg="config connector: local passwords enabled"
time="2020-02-13T18:30:14Z" level=info msg="config skipping approval screen"
time="2020-02-13T18:30:14Z" level=info msg="keys expired, rotating"
time="2020-02-13T18:30:14Z" level=info msg="keys rotated, next rotation: 2020-02-14 00:30:14.562140822 +0000 UTC"
time="2020-02-13T18:30:14Z" level=info msg="listening (http) on 0.0.0.0:5556"
time="2020-02-13T18:41:57Z" level=info msg="login successful: connector \"local\", username=\"admin\", email=\"admin@kubeflow.org\", groups=[]"
```

**Comment by rafaelbarreto87** [comment]
Update: after chatting with @yanniszark in the Slack channel, I updated the dex image to the latest version (`quay.io/dexidp/dex:v2.22.0`) and it worked without a problem

Thanks @yanniszark.

**Comment by yanniszark** [comment]
Glad to hear the issue is fixed 😄 
/close

**Comment by rafaelbarreto87** [comment]
To be clear, the fix suggested by @yanniszark worked for me, but the issue is actually not fixed in the repository. Other folks in a similar situation will still have the same issue. We need to change it in the repo. I'll see if I submit a PR with the updated version.

**Comment by yanniszark** [comment]
@rafaelbarreto87 are you sure?
I inspected the Dex manifests and it seems to me that the kustomization changes the image to a new, correct one:
https://github.com/kubeflow/manifests/blob/7809d996e965d45a75288faae053cad2180e4a79/dex-auth/dex-crds/base/kustomization.yaml#L81-L84

Still, we'd like to update the Dex image to an official one now that a release is available, so feel free to open a PR.

**Comment by rafaelbarreto87** [comment]
Oh. Interesting... I dig a bit and figured out what happened since I started from the latest manifests. Leaving it here since others might run into a similar issue. Since I'm in a private cluster, I had to move all the images to our private cluster. I changed the `dex` image in `kustomize/dex/base/deployment.yaml`, which was pointing to `quay.io/coreos/dex:v2.9.0`, to point to `gcr.io/{MY_PROJECT}/3rdparty/quay.io/coreos/dex:v2.9.0`.

However, I forgot to change `kustomize/dex/base/kustomization.yaml`. This created a mismatch and the patched `newName` and `newTag` wasn't applied since there weren't any `quay.io/coreos/dex` reference anymore. Therefore, when I applied the config, it used `quay.io/coreos/dex:v2.9.0` which was broken.
